export const LOADING_SCREEN = 'LOADING_SCREEN';
export const AUTH_STACK = 'AUTH_STACK';
export const APP_STACK = 'APP_STACK';

export const LANDING_SCREEN = 'LANDING_SCREEN';
export const SIGN_IN_SCREEN = 'SIGN_IN_SCREEN';
export const CREATE_ACCOUNT_SCREEN = 'CREATE_ACCOUNT_SCREEN';
export const FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD_SCREEN';
export const RESET_PASSWORD_SCREEN = 'RESET_PASSWORD_SCREEN';

export const WORKOUTS_STACK = 'WORKOUTS_STACK';
export const DAIRY_STACK = 'DAIRY_STACK';
export const MY_WEEK_STACK = 'MY_WEEK_STACK';
export const EXERCISES_STACK = 'EXERCISES_STACK';
export const SETTINGS_STACK = 'SETTINGS_STACK';

export const WORKOUTS_SCREEN = 'WORKOUTS_SCREEN';
export const CREATE_WORKOUT_SCREEN = 'CREATE_WORKOUT_SCREEN';

export const DAIRY_SCREEN = 'DAIRY_SCREEN';
export const MY_WEEK_SCREEN = 'MY_WEEK_SCREEN';
export const EXERCISES_SCREEN = 'EXERCISES_SCREEN';
export const SETTINGS_SCREEN = 'SETTINGS_SCREEN';
